name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v1.1.1
      - name: Install dependencies
        run: dotnet restore
      - name: Build 
        run: |
          dotnet publish --configuration Release \
            /p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} \
            /p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} \
            /p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }} \
            /p:Version=${{ steps.gitversion.outputs.nuGetVersion }}
      - name: Test
        run: |
          dotnet test --configuration Release --no-build --verbosity normal
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NuGets
          path: |
            source/**/Release/*.nupkg
            source/**/Release/*.snupkg
      - name: Upload to NuGet
        run: |
          dotnet nuget push "source/**/Release/*.nupkg" \
            --source https://api.nuget.org/v3/index.json \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --skip-duplicate